name: Docker Build Validate

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build-validate:
    name: Validate docker build
    runs-on: ubuntu-latest
    steps:
      - name: Project checkout
        uses: actions/checkout@v3
        id: project_checkout

      - name: Image tag
        run: |
          echo "IMAGE_TAG=${{ secrets.DOCKER_IMAGE_NAME }}:$(echo ${GITHUB_REF_NAME//v})" >> "$GITHUB_ENV"
          echo "$IMAGE_TAG"
        id: image_tag

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKER_IMAGE_NAME }}:latest

