name: Docker Build Push

on:
  push:
    tags:
      - v*

defaults:
  run:
    shell: bash

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Project checkout
        uses: actions/checkout@v2
        id: project_checkout

      - name: Docker build
        run: docker build -t ${{ secrets.DOCKER_IMAGE_NAME }}:latest .
        id: docker_build

