name: Docker Build Push

on:
  push:
    tags:
      - 'v*.*.*'

defaults:
  run:
    shell: bash

jobs:
  build-push:
    name: Docker build and push
    runs-on: ubuntu-latest
    steps:

      - name: Project checkout
        uses: actions/checkout@v3
        id: project_checkout

      - name: Image tag
        run: echo "IMAGE_TAG=${{ secrets.DOCKER_IMAGE_NAME }}:$(echo ${GITHUB_REF_NAME//v})" >> "$GITHUB_ENV"
        id: image_tag

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
        id: docker_login

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG }}